site_name: Cardano UTXO CSMT Documentation
site_url: https://paolino.github.io/cardano-utxo-csmt/
repo_url: https://github.com/paolino/cardano-utxo-csmt

theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.indexes
    - toc.integrate
    - content.code.copy
    - navigation.path

plugins:
  - search
  - asciinema-player

markdown_extensions:
  - callouts