site_name: Cardano UTXO CSMT
site_url: https://paolino.github.io/cardano-utxo-csmt/
repo_url: https://github.com/paolino/cardano-utxo-csmt

theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.indexes
    - toc.integrate
    - content.code.copy
    - navigation.path

plugins:
  - search
  - asciinema-player
  - swagger-ui-tag
  - macros

markdown_extensions:
  - callouts
  - attr_list
  - md_in_html
  - pymdownx.snippets:
      base_path: !relative
      check_paths: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Mithril Bootstrap: mithril-bootstrap.md
  - Architecture: architecture.md
  - API Reference:
      - Swagger UI: swagger-ui.md