site_name: Cardano UTXO CSMT Documentation
site_url: https://paolino.github.io/cardano-utxo-csmt/
repo_url: https://github.com/paolino/cardano-utxo-csmt

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true

plugins:
  - search
  - asciinema-player

markdown_extensions:
  - callouts