site_name: Cardano UTXO CSMT Documentation
site_url: https://paolino.github.io/cardano-utxo-csmt/
repo_url: https://github.com/paolino/cardano-utxo-csmt

theme:
  mkdocs

plugins:
  - search
  - asciinema-player

markdown_extensions:
  - callouts